/* ═══════════════════════════════════════════
   data.js — All product data & dummy content
   ═══════════════════════════════════════════ */

const DB = {

  categories: [
    { id: 'all',        label: 'All Items',         emoji: '🏪' },
    { id: 'creative',   label: 'Creative Arts',     emoji: '🎨' },
    { id: 'outdoor',    label: 'Outdoor & Nature',  emoji: '🏕️' },
    { id: 'stem',       label: 'Technical & STEM',  emoji: '🔬' },
    { id: 'sports',     label: 'Physical Sports',   emoji: '🏋️' },
    { id: 'culinary',   label: 'Culinary Arts',     emoji: '🍳' },
    { id: 'gaming',     label: 'Gaming & Strategy', emoji: '🎲' },
    { id: 'collecting', label: 'Collecting',        emoji: '🏆' },
  ],

  products: [
    // ── Creative Arts ──
    { id: 1,  cat: 'creative',   name: 'Fujifilm X100V Silver',        emoji: '📷', bg: 'linear-gradient(135deg,#E8D5B7,#C9A87A)', img: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=300&fit=crop', price: 55900, orig: 72000, cond: 'Excellent', rating: 4.9, reviews: 47, seller: 'Jerome Lim', sellerId: 1, badge: 'hot',   desc: 'Iconic compact camera, shutter perfectly responsive. Minor cosmetic wear on base plate only.' },
    { id: 2,  cat: 'creative',   name: 'Leica M6 TTL Black',           emoji: '🎞️', bg: 'linear-gradient(135deg,#D1D5DB,#9CA3AF)', img: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=400&h=300&fit=crop', price: 198000, orig: 230000, cond: 'Very Good', rating: 4.7, reviews: 89, seller: 'Maria Reyes', sellerId: 2, badge: 'top',   desc: 'Legendary rangefinder, meter fully functional. Comes with original box and strap.' },
    { id: 3,  cat: 'creative',   name: 'Sony ZV-E10 Kit 16-50mm',      emoji: '🎥', bg: 'linear-gradient(135deg,#BFDBFE,#60A5FA)', img: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=300&fit=crop', price: 24500, orig: 32000, cond: 'Like New',  rating: 5.0, reviews: 12, seller: 'Tony Cruz',  sellerId: 3, badge: 'new',   desc: 'Barely used vlogging powerhouse. No scratches, sensor pristine. Box and all accessories included.' },
    { id: 4,  cat: 'creative',   name: 'Rode VideoMic Pro+',           emoji: '🎙️', bg: 'linear-gradient(135deg,#FDE68A,#F59E0B)', img: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400&h=300&fit=crop', price: 8900,  orig: 12500, cond: 'Very Good', rating: 4.8, reviews: 23, seller: 'Sofia Navarro', sellerId: 4, badge: null,   desc: 'Professional on-camera mic, Rycote Lyre mount intact. Low noise, crystal clear audio.' },
    { id: 5,  cat: 'creative',   name: 'Wacom Intuos Pro M',           emoji: '🖊️', bg: 'linear-gradient(135deg,#E0E7FF,#818CF8)', img: 'https://images.unsplash.com/photo-1629429408209-1f912961dbd8?w=400&h=300&fit=crop', price: 14200, orig: 19500, cond: 'Good',      rating: 4.6, reviews: 34, seller: 'Jerome Lim', sellerId: 1, badge: null,   desc: 'Professional drawing tablet with multi-touch. All nibs included, working perfectly.' },
    { id: 6,  cat: 'creative',   name: 'Canon EOS R50 Body',           emoji: '📸', bg: 'linear-gradient(135deg,#FED7E2,#F472B6)', img: 'https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?w=400&h=300&fit=crop', price: 38000, orig: 48000, cond: 'Excellent', rating: 4.9, reviews: 18, seller: 'Maria Reyes', sellerId: 2, badge: 'new',   desc: 'Mirrorless with 24.2MP sensor. Only 1,200 shutter count. Perfect for aspiring photographers.' },

    // ── Outdoor & Nature ──
    { id: 7,  cat: 'outdoor',    name: 'Nikon Monarch M5 8x42',        emoji: '🔭', bg: 'linear-gradient(135deg,#D1FAE5,#34D399)', img: 'https://images.unsplash.com/photo-1621451537084-482c73073a0f?w=400&h=300&fit=crop', price: 15800, orig: 22000, cond: 'Excellent', rating: 4.9, reviews: 29, seller: 'Tony Cruz',  sellerId: 3, badge: null,   desc: 'Premium birdwatching binoculars, ED glass, dielectric coating. Zero fungus or haze.' },
    { id: 8,  cat: 'outdoor',    name: 'MSR Hubba Hubba NX 2-Person',  emoji: '⛺', bg: 'linear-gradient(135deg,#FDE68A,#FCA5A5)', img: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400&h=300&fit=crop', price: 12400, orig: 18000, cond: 'Good',      rating: 4.5, reviews: 41, seller: 'Ryan Santos', sellerId: 5, badge: null,   desc: 'Used twice on weekend trips. Poles and stakes all present. Minor staining on rainfly.' },
    { id: 9,  cat: 'outdoor',    name: 'Garmin GPSMAP 65s',            emoji: '🗺️', bg: 'linear-gradient(135deg,#BFDBFE,#3B82F6)', img: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&h=300&fit=crop', price: 18500, orig: 24000, cond: 'Very Good', rating: 4.7, reviews: 15, seller: 'Sofia Navarro', sellerId: 4, badge: null,   desc: 'Handheld GPS with multi-band GNSS. Screen protector applied, no scratches.' },
    { id: 10, cat: 'outdoor',    name: 'Black Diamond Spot 350 Headlamp',emoji:'🔦', bg: 'linear-gradient(135deg,#E0F2FE,#7DD3FC)', img: 'https://images.unsplash.com/photo-1590073242678-70ee3fc28e8e?w=400&h=300&fit=crop', price: 2200,  orig: 3200,  cond: 'Like New',  rating: 4.8, reviews: 8,  seller: 'Ryan Santos', sellerId: 5, badge: 'new',   desc: 'Used only once. All batteries replaced. 350 lumens, IPX8 waterproof.' },

    // ── Technical & STEM ──
    { id: 11, cat: 'stem',       name: 'Celestron NexStar 8SE',        emoji: '🌌', bg: 'linear-gradient(135deg,#E9D5FF,#7C3AED)', img: 'https://images.unsplash.com/photo-1532978379173-523e16f371f2?w=400&h=300&fit=crop', price: 64000, orig: 89000, cond: 'Very Good', rating: 4.8, reviews: 22, seller: 'Jerome Lim', sellerId: 1, badge: 'top',   desc: 'Computerized Schmidt-Cassegrain telescope. GoTo aligned and working perfectly. All accessories.' },
    { id: 12, cat: 'stem',       name: 'Raspberry Pi 4 Model B 8GB Kit', emoji:'🖥️', bg: 'linear-gradient(135deg,#FEE2E2,#F87171)', img: 'https://images.unsplash.com/photo-1629292921160-93ed4e344bce?w=400&h=300&fit=crop', price: 5400,  orig: 7200,  cond: 'Excellent', rating: 4.9, reviews: 56, seller: 'Ryan Santos', sellerId: 5, badge: null,   desc: 'Complete kit with case, PSU, heatsinks, SD card with Raspbian pre-installed.' },
    { id: 13, cat: 'stem',       name: 'Fluke 87V True RMS Multimeter',emoji: '⚡', bg: 'linear-gradient(135deg,#FEF3C7,#FDE68A)', img: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?w=400&h=300&fit=crop', price: 8200,  orig: 11500, cond: 'Good',      rating: 4.6, reviews: 31, seller: 'Tony Cruz',  sellerId: 3, badge: null,   desc: 'Industrial-grade multimeter, all leads included. Calibrated 6 months ago.' },
    { id: 14, cat: 'stem',       name: 'Arduino Mega 2560 + Starter Kit', emoji:'🤖', bg: 'linear-gradient(135deg,#D1FAE5,#6EE7B7)', img: 'https://images.unsplash.com/photo-1553406830-ef2513450d76?w=400&h=300&fit=crop', price: 3200,  orig: 4800,  cond: 'Very Good', rating: 4.7, reviews: 44, seller: 'Maria Reyes', sellerId: 2, badge: null,   desc: 'Complete starter kit with breadboards, sensors, wires. Perfect for learning embedded systems.' },

    // ── Physical Sports ──
    { id: 15, cat: 'sports',     name: 'Titleist AP2 Iron Set 4-PW',   emoji: '⛳', bg: 'linear-gradient(135deg,#ECFDF5,#86EFAC)', img: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=400&h=300&fit=crop', price: 28000, orig: 42000, cond: 'Good',      rating: 4.7, reviews: 19, seller: 'Sofia Navarro', sellerId: 4, badge: null,   desc: 'Forged irons with Vokey wedges. Regripped last month. Cosmetic wear on soles only.' },
    { id: 16, cat: 'sports',     name: 'Trek Marlin 5 MTB 2021',       emoji: '🚵', bg: 'linear-gradient(135deg,#FEF9C3,#FCD34D)', img: 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=400&h=300&fit=crop', price: 35000, orig: 52000, cond: 'Very Good', rating: 4.8, reviews: 27, seller: 'Ryan Santos', sellerId: 5, badge: null,   desc: '29er hardtail, freshly tuned and cleaned. New brake pads and chain installed.' },
    { id: 17, cat: 'sports',     name: 'Speedo Fastskin Elite Mirror Goggle',emoji:'🥽', bg:'linear-gradient(135deg,#DBEAFE,#93C5FD)', img: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=400&h=300&fit=crop', price: 2800,  orig: 4200,  cond: 'Like New',  rating: 4.9, reviews: 11, seller: 'Maria Reyes', sellerId: 2, badge: 'new',   desc: 'Competition-grade goggles, anti-fog lens perfect. Used only in 2 meets.' },
    { id: 18, cat: 'sports',     name: 'Yonex Arcsaber 11 Pro Badminton',emoji:'🏸', bg:'linear-gradient(135deg,#FCE7F3,#F9A8D4)', img: 'https://images.unsplash.com/photo-1613918431703-aa50889e3be2?w=400&h=300&fit=crop', price: 7500,  orig: 11000, cond: 'Very Good', rating: 4.6, reviews: 33, seller: 'Jerome Lim', sellerId: 1, badge: null,   desc: 'Strung at 26lbs BG80. Grip replaced. Minor paint chip near handle, no structural damage.' },

    // ── Culinary Arts ──
    { id: 19, cat: 'culinary',   name: 'KitchenAid Stand Mixer 5qt Artisan', emoji:'🍰', bg:'linear-gradient(135deg,#FEF3C7,#FDE68A)', img: 'https://images.unsplash.com/photo-1594385208974-2f8bb07b7a26?w=400&h=300&fit=crop', price: 18000, orig: 26000, cond: 'Very Good', rating: 4.8, reviews: 38, seller: 'Sofia Navarro', sellerId: 4, badge: null,   desc: 'Empire Red, all original attachments. Motor strong, bowl shows light use scratches only.' },
    { id: 20, cat: 'culinary',   name: 'De Buyer Mineral B Carbon Steel Pan', emoji:'🍳', bg:'linear-gradient(135deg,#D1D5DB,#6B7280)', img: 'https://images.unsplash.com/photo-1585442231018-1e2d5e0a5c3d?w=400&h=300&fit=crop', price: 3800,  orig: 5500,  cond: 'Excellent', rating: 4.9, reviews: 52, seller: 'Ryan Santos', sellerId: 5, badge: 'top',   desc: 'Perfectly seasoned 28cm pan. Non-stick as cast iron. Lifetime cookware at a fraction of cost.' },
    { id: 21, cat: 'culinary',   name: 'Breville Barista Express BES870',   emoji:'☕', bg:'linear-gradient(135deg,#F5F5F4,#D4D4D8)', img: 'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=400&h=300&fit=crop', price: 32000, orig: 48000, cond: 'Good',      rating: 4.7, reviews: 24, seller: 'Tony Cruz',  sellerId: 3, badge: null,   desc: 'Integrated grinder, all portafilters included. Descaled and full service done last month.' },
    { id: 22, cat: 'culinary',   name: 'Victorinox Fibrox Pro 8" Chef Knife', emoji:'🔪', bg:'linear-gradient(135deg,#E2E8F0,#94A3B8)', img: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=400&h=300&fit=crop', price: 2400,  orig: 3500,  cond: 'Very Good', rating: 4.8, reviews: 67, seller: 'Maria Reyes', sellerId: 2, badge: null,   desc: 'Professionally sharpened. Edge holds well. Handle sanitized and clean. Perfect workhorse knife.' },

    // ── Gaming & Strategy ──
    { id: 23, cat: 'gaming',     name: 'Nintendo Switch OLED White',   emoji: '🎮', bg: 'linear-gradient(135deg,#FEF9C3,#FCD34D)', img: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=400&h=300&fit=crop', price: 18500, orig: 24000, cond: 'Excellent', rating: 4.9, reviews: 44, seller: 'Jerome Lim', sellerId: 1, badge: 'hot',   desc: 'Screen perfect, no dead pixels or scratches. Includes dock, Pro Controller, and 3 games.' },
    { id: 24, cat: 'gaming',     name: 'Vital Lacerda Lisboa Deluxe',  emoji: '🗺️', bg: 'linear-gradient(135deg,#DBEAFE,#A5F3FC)', img: 'https://images.unsplash.com/photo-1611371805429-8b5c1b2c34ba?w=400&h=300&fit=crop', price: 6800,  orig: 9500,  cond: 'Like New',  rating: 5.0, reviews: 9,  seller: 'Sofia Navarro', sellerId: 4, badge: 'new',   desc: 'Played once at BGG Con. All components mint, sleeved. One of the best games ever made.' },
    { id: 25, cat: 'gaming',     name: 'Keychron Q3 QMK Custom KB',    emoji: '⌨️', bg: 'linear-gradient(135deg,#F3E8FF,#C4B5FD)', img: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=400&h=300&fit=crop', price: 9800,  orig: 14000, cond: 'Very Good', rating: 4.8, reviews: 31, seller: 'Ryan Santos', sellerId: 5, badge: null,   desc: 'Gateron G Pro Yellow switches, lubed. South-facing PCB, no RGB bleed. QMK configured.' },
    { id: 26, cat: 'gaming',     name: 'Chess.com Membership + DGT Board', emoji:'♟️', bg:'linear-gradient(135deg,#F5F5F4,#D4D4D8)', img: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=400&h=300&fit=crop', price: 5200,  orig: 8000,  cond: 'Good',      rating: 4.5, reviews: 16, seller: 'Tony Cruz',  sellerId: 3, badge: null,   desc: 'DGT Smart Board with Bluetooth. 1-year Chess.com Diamond included. Perfect for serious players.' },

    // ── Collecting ──
    { id: 27, cat: 'collecting', name: 'PSA 9 Charizard Base Set Holo', emoji: '🐉', bg: 'linear-gradient(135deg,#FEF3C7,#FCA5A5)', img: 'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=400&h=300&fit=crop', price: 42000, orig: 55000, cond: 'PSA 9', rating: 5.0, reviews: 7,  seller: 'Maria Reyes', sellerId: 2, badge: 'top',   desc: 'Professionally graded. Centered, sharp corners, no print defects. Certificate of authenticity.' },
    { id: 28, cat: 'collecting', name: 'Seiko SKX007 Diver 200m',       emoji: '⌚', bg: 'linear-gradient(135deg,#DBEAFE,#60A5FA)', img: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=300&fit=crop', price: 28500, orig: 36000, cond: 'Very Good', rating: 4.8, reviews: 42, seller: 'Ryan Santos', sellerId: 5, badge: null,   desc: 'Vintage diver icon. Recently serviced, new crown seal. Case polished, bezel sharp.' },
    { id: 29, cat: 'collecting', name: 'LEGO Creator Expert 10294 Titanic', emoji:'🚢', bg:'linear-gradient(135deg,#E0E7FF,#A5B4FC)', img: 'https://images.unsplash.com/photo-1587654780291-39c9404d7dd0?w=400&h=300&fit=crop', price: 22000, orig: 28000, cond: 'Sealed',    rating: 4.9, reviews: 14, seller: 'Jerome Lim', sellerId: 1, badge: 'new',   desc: 'Factory sealed, never opened. Receipt and box in perfect condition. Price includes shipping.' },
    { id: 30, cat: 'collecting', name: 'Marvel Funko Pop Galactus #1 Convention Exclusive', emoji:'🦸', bg:'linear-gradient(135deg,#F5D0A9,#E88B5E)', img: 'https://images.unsplash.com/photo-1608889825205-eebdb9fc5806?w=400&h=300&fit=crop', price: 8900, orig: 12000, cond: 'Mint in Box', rating: 4.7, reviews: 21, seller: 'Sofia Navarro', sellerId: 4, badge: null,   desc: 'SDCC exclusive, never displayed. Original bag and sticker included. Extremely limited run.' },
  ],

  sellers: [
    { id: 1, name: 'Jerome Lim',    initials: 'JL', color: '#D97706', city: 'Metro Manila', rating: 5.0, sales: 234, badge: '🏅 Super Seller', cats: ['Creative Arts','Gaming'] },
    { id: 2, name: 'Maria Reyes',   initials: 'MR', color: '#059669', city: 'Cebu City',     rating: 4.9, sales: 189, badge: '⚡ Fast Ship',   cats: ['Creative Arts','Collecting'] },
    { id: 3, name: 'Tony Cruz',     initials: 'TC', color: '#7C3AED', city: 'Davao City',    rating: 4.9, sales: 156, badge: '✅ Verified',    cats: ['Technical','Culinary'] },
    { id: 4, name: 'Sofia Navarro', initials: 'SN', color: '#DC2626', city: 'BGC Taguig',    rating: 4.8, sales: 98,  badge: '📸 Pro Seller', cats: ['Sports','Gaming','Collecting'] },
    { id: 5, name: 'Ryan Santos',   initials: 'RS', color: '#0284C7', city: 'Quezon City',   rating: 4.8, sales: 112, badge: '🌟 Trusted',    cats: ['Outdoor','Technical','Sports'] },
  ],

  notifications: [
    { id: 1, icon: '📦', text: '<strong>Your order #HL-2026-00291 has shipped!</strong> Tony Cruz sent your Breville Barista via J&T Express.', time: '2 min ago', unread: true },
    { id: 2, icon: '💰', text: '<strong>Price drop alert!</strong> Fujifilm X100V dropped ₱3,000 — it\'s on your watchlist!', time: '14 min ago', unread: true },
    { id: 3, icon: '⭐', text: '<strong>New review on your listing.</strong> Someone left a 5-star review on your Wacom Intuos listing.', time: '1 hour ago', unread: true },
    { id: 4, icon: '🤝', text: '<strong>Ryan Santos accepted your offer.</strong> MSR Hubba Hubba NX is ready to checkout!', time: '2 hours ago', unread: true },
    { id: 5, icon: '💬', text: '<strong>Maria Reyes replied to your question</strong> about the Leica M6 condition.', time: '3 hours ago', unread: false },
    { id: 6, icon: '✅', text: '<strong>Listing verified!</strong> Your Nintendo Switch OLED passed peer review and is now live.', time: '5 hours ago', unread: false },
    { id: 7, icon: '🎉', text: '<strong>Welcome to HobbyLoop!</strong> Your account is fully set up. Start exploring 12,400+ items.', time: 'Yesterday', unread: false },
    { id: 8, icon: '🏆', text: '<strong>You\'re now a Trusted Buyer!</strong> 10 successful purchases with 5-star ratings.', time: '2 days ago', unread: false },
  ],

  communityPosts: [
    { id: 1, userId: 1, author: 'Jerome Lim', handle: '@jerolim', initials: 'JL', color: '#D97706', time: '2 min ago', text: 'Just finished CLA on this Olympus OM-1. Shutter sounds like butter. Mirror damper replaced, light seals fresh. Ready for another 50 years 📷', productId: null, likes: 47, comments: 12, liked: false },
    { id: 2, userId: 2, author: 'Maria Reyes', handle: '@mariaphotos', initials: 'MR', color: '#059669', time: '18 min ago', text: 'Film tip: CineStill 800T in tungsten lighting is absolutely magical for food photography. The halation around point lights is *chef\'s kiss* 🍳✨', productId: 20, likes: 83, comments: 24, liked: false },
    { id: 3, userId: 5, author: 'Ryan Santos', handle: '@ryansummits', initials: 'RS', color: '#0284C7', time: '1 hour ago', text: 'Sold the Nikon P1000 and upgrading to this Celestron. Night sky in Batad last weekend was life-changing. Highly recommend getting into astronomy!', productId: 11, likes: 62, comments: 19, liked: false },
    { id: 4, userId: 4, author: 'Sofia Navarro', handle: '@sofiacooks', initials: 'SN', color: '#DC2626', time: '3 hours ago', text: 'Hot take: the De Buyer carbon steel pan beats cast iron in every single use case except maybe deep frying. Change my mind. 🍳 Listing mine because upgrading to a larger size.', productId: 20, likes: 119, comments: 38, liked: true },
    { id: 5, userId: 3, author: 'Tony Cruz', handle: '@tonytechlab', initials: 'TC', color: '#7C3AED', time: '5 hours ago', text: 'Finally built a proper electronics workspace with my Fluke multimeter and the Arduino kit. Running first IoT project this weekend — soil moisture sensor for my herb garden 🌱⚡', productId: 13, likes: 34, comments: 7, liked: false },
    { id: 6, userId: 1, author: 'Jerome Lim', handle: '@jerolim', initials: 'JL', color: '#D97706', time: '8 hours ago', text: 'PSA for collectors: Protective sleeves are non-negotiable. Just pulled a near-mint charizard from a Ziploc bag 🤦‍♂️ The penny sleeve alone can double resale value over 5 years.', productId: 27, likes: 201, comments: 67, liked: false },
  ],

  orders: [],
};
